
### health
GET http://localhost:8080/health


### retrieve all meettings
GET http://localhost:8080/meetings


### retireve a meeting associated with id
GET http://localhost:8080/meetings/1


### register a meeting
POST http://localhost:8080/meetings
Content-Type: application/json

{
  "name": "Happy Halloween!",
  "description": "Have an happy hour with your classmate",
  "qrUrl": "www.google.com",
  "eventAt": "1698800548085",
  "registerNow": true
}

### update a meeting
PUT http://localhost:8080/meetings/1
Content-Type: application/json

{
  "name": "Happy Halloween!",
  "description": "Have an happy hour with your classmate",
  "registerNow": true,
  "attendees": [{
    "name": "Lucy",
    "email": "hlee109@dons.usfca.edu",
    "phone": "6267863192"
  },{
    "name": "Haebin",
    "email": "hblee8080@gmail.com",
    "phone": "01024226891"
  },{
    "name": "luckylucy",
    "email": "luckylucy0717@gmail.com",
    "phone": "6267863192"
  }]
}


### confirm
POST http://localhost:8080/meetings/1/attendees/confirm
Content-Type: application/json

{
  "name": "Lucy"
}